# Generated by Django 6.0 on 2026-06-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_binmovement_cliente_delete_cliente'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bin_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_presentations', to='bins.bintype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='productos.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'bin_type'), name='unique_product_bin_presentation')],
            },
        ),
    ]
