# Generated by Django 6.0 on 2026-07-07 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_binmovement_cliente_delete_cliente'),
        ('productos', '0002_productpresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpresentation',
            name='cantidad_envase_contenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='cantidad_por_envase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='envase_contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contenido_en_presentaciones', to='bins.bintype'),
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
