# Generated by Django 6.0 on 2026-09-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productpresentation_cantidad_envase_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpresentation',
            name='tipo_cobro',
            field=models.CharField(choices=[('envase', 'Por envase'), ('kilo', 'Por kilo')], default='envase', max_length=20),
        ),
    ]
