# Generated by Django 6.0 on 2026-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_bintype_usuario'),
        ('productos', '0004_productpresentation_tipo_cobro'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productpresentation',
            name='unique_product_bin_presentation',
        ),
        migrations.AddConstraint(
            model_name='productpresentation',
            constraint=models.UniqueConstraint(fields=('product', 'bin_type', 'tipo_cobro'), name='unique_product_bin_billing_presentation'),
        ),
    ]
