# Generated by Django 6.0 on 2026-09-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario asociado'), ('admin', 'Administrador')], default='usuario', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asociados', to=settings.AUTH_USER_MODEL)),
                ('usuario_asociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_titular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titular', 'usuario_asociado'), name='unique_titular_usuario_asociado')],
            },
        ),
    ]
