# Generated by Django 6.0 on 2026-03-02 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0004_sale_cliente_sale_facturada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_rut', models.CharField(max_length=20)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ventas.sale')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
