# Generated by Django 6.0 on 2026-02-17 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='bin_type',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inventory',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='nombre',
            field=models.CharField(default='item', max_length=150),
            preserve_default=False,
        ),
    ]
