# Generated by Django 6.0 on 2026-02-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
        ('inventario', '0002_remove_inventory_bin_type_remove_inventory_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='bins.bintype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
