# Generated by Django 6.0 on 2026-05-20 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_binmovement_referencia'),
        ('inventario', '0005_alter_inventory_options_alter_inventory_product_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('usuario', 'product', 'bin')},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
