# Generated by Django 6.0 on 2026-06-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_options_remove_pago_factura_and_more'),
        ('ventas', '0006_remove_sale_facturada_saleitem_bins_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='ventas.sale'),
        ),
    ]
