# Generated by Django 6.0 on 2026-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bintype',
            name='tipo',
            field=models.CharField(choices=[('BIN', 'Bin'), ('PALLET', 'Pallet'), ('CAJA', 'Caja')], default='BIN', max_length=10),
        ),
    ]
