# Generated by Django 6.0 on 2026-05-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_bintype_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='binmovement',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
