# Generated by Django 6.0 on 2026-05-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_binmovement_referencia'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binmovement',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.client'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
