# Generated by Django 6.0 on 2026-07-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_binmovement_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bintype',
            name='tipo',
            field=models.CharField(choices=[('BIN', 'Bin'), ('PALLET', 'Pallet'), ('CAJA', 'Caja'), ('GAMELA', 'Gamela'), ('BANDEJA', 'Bandeja'), ('SACO', 'Saco'), ('BOLSA', 'Bolsa'), ('OTRO', 'Otro')], default='BIN', max_length=10),
        ),
    ]
