# Generated by Django 6.0 on 2026-02-21 15:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0002_alter_saleitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('referencia', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bins.bintype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
