# Generated by Django 6.0 on 2026-02-28 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0003_sale_iva_alter_sale_numero_inventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clientes.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
    ]
