# Generated by Django 6.0 on 2026-03-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0004_sale_cliente_sale_facturada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clientes.client'),
        ),
    ]
