# Generated by Django 6.0 on 2026-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_sale_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='facturada',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='bins_cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
