# Generated by Django 6.0 on 2026-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_sale_facturada_saleitem_bins_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='kilos_pesados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tipo_cobro_snapshot',
            field=models.CharField(default='envase', max_length=20),
        ),
    ]
